# Generated by Django 5.0.3 on 2024-03-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='./media/default.jpg', upload_to='head_image/%Y/%m', verbose_name='用户头像'),
        ),
    ]
