# Generated by Django 5.0.3 on 2024-03-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='click_nums',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='fav_nums',
        ),
    ]
