# Generated by Django 5.0.3 on 2024-08-11 18:35

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='小节名称')),
                ('learning_space', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='学习空间')),
                ('file', models.FileField(blank=True, null=True, upload_to='course/resourse/%Y/%m', verbose_name='课件资料')),
            ],
            options={
                'verbose_name': '课程小节',
                'verbose_name_plural': '课程小节',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=50, verbose_name='课程名')),
                ('desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='课程描述')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('detail', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='课程详情')),
                ('image', models.ImageField(default='course_images.jpg', upload_to='courses/%Y/%m', verbose_name='封面图')),
                ('status', models.BooleanField(default=True, verbose_name='课程状态')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '课程类别',
                'verbose_name_plural': '课程类别',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=100, verbose_name='章节名')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(max_length=100, verbose_name='通知标题')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='通知详情')),
            ],
            options={
                'verbose_name': '课程通知',
                'verbose_name_plural': '课程通知',
            },
        ),
    ]
