# Generated by Django 5.0.3 on 2024-04-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0006_alter_course_youneed_know'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=True, verbose_name='课程状态'),
        ),
    ]
