# Generated by Django 5.0.3 on 2024-04-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_remove_userprofile_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', '男'), ('2', '女')], max_length=6, null=True,
                                   verbose_name='性别'),
        ),
    ]
