# Generated by Django 5.0.3 on 2024-04-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', '1'), ('女', '2')], max_length=1, null=True,
                                   verbose_name='性别'),
        ),
    ]
