# Generated by Django 5.0.3 on 2024-03-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.course',),
        ),
    ]
