# Generated by Django 5.0.3 on 2024-03-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False, verbose_name='是否有作用'),
        ),
    ]
