# Generated by Django 5.0.3 on 2024-03-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '作业', 'verbose_name_plural': '作业'},
        ),
    ]
