# Generated by Django 5.0.3 on 2024-03-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskFile',
        ),
    ]
