# Generated by Django 5.0.3 on 2024-03-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_remove_task_taskfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
