# Generated by Django 5.0.3 on 2024-03-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_remove_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(2, '课程'), (1, '课程机构'), (3, '讲师')], default=1, verbose_name='收藏类型'),
        ),
    ]
