# Generated by Django 5.0.3 on 2024-04-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0004_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='teacher_img_default.jpg', upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
